language: android
android:
  components:
    - build-tools-19.1.0
    - android-19

sudo: required

addons:
  hostname: keenclient-java

jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

before_install:

  # Install packages needed to execute Android tools on 64-bit Linux.
  - ./install_prereqs.sh

env:
  - TERM=dumb

install:
  - ./gradlew assemble

script:
  - ./gradlew check
